## **Import**

In [2]:
import pandas as pd

## **Load Dataset**

In [3]:
df = pd.read_csv("data/titanic.csv")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

## **Create New Features**

In [4]:
df['family_size'] = df['sibsp'] + df['parch'] + 1

In [5]:
df['is_alone'] = df['family_size'].apply(lambda x: 1 if x == 1 else 0)

## **Feature Transformation**

In [6]:
df['fare_per_person'] = df['fare'] / df['family_size']

## **Binning**

In [7]:
df['age_group'] = pd.cut(
    df['age'],
    bins=[0, 12, 18, 35, 60, 100],
    labels=['child', 'teen', 'young_adult', 'adult', 'senior']
)

## **Encode New Feature**

In [8]:
df['age_group_encoded'] = df['age_group'].cat.codes

## **Apply Lambda**

In [9]:
df['high_fare'] = df['fare'].apply(lambda x: 1 if x > 50 else 0)

## **Check New Feaures**

In [10]:
df[['family_size', 'is_alone', 'fare_per_person', 'age_group', 'high_fare']].head()

   family_size  is_alone  fare_per_person    age_group  high_fare
0            2         0          3.62500  young_adult          0
1            2         0         35.64165        adult          1
2            1         1          7.92500  young_adult          0
3            2         0         26.55000  young_adult          1
4            1         1          8.05000  young_adult          0

## **Save Dataset**

In [11]:
df.to_csv("data/titanic_featured.csv", index=False)