## **Import**

In [1]:
import pandas as pd
import numpy as np

## **Create Dataset**

In [2]:
np.random.seed(42)

data = {
    "student": [f"Student_{i}" for i in range(1, 101)],
    "class": np.random.choice(["A", "B", "C"], 100),
    "subject": np.random.choice(["Math", "Science", "English"], 100),
    "marks": np.random.randint(30, 100, 100)
}

df = pd.DataFrame(data)
df.head()

     student class  subject  marks
0  Student_1     C  English     81
1  Student_2     A  English     91
2  Student_3     C  English     87
3  Student_4     C     Math     81
4  Student_5     A  English     41

## **Save Dataset**

In [3]:
df.to_csv("data/student_data.csv", index=False)

## **Load Dataset**

In [4]:
df = pd.read_csv("data/student_data.csv")

## **Average Marks per Subject**

In [5]:
avg_marks = df.groupby("subject")["marks"].mean().reset_index()
avg_marks

   subject      marks
0  English  62.571429
1     Math  68.212121
2  Science  58.920000

## **Average Marks per Class**

In [6]:
class_avg = df.groupby("class")["marks"].mean().reset_index()
class_avg

  class      marks
0     A  64.454545
1     B  63.500000
2     C  62.548387

## **Topper(Highest Marks)**

In [7]:
topper = df.sort_values(by="marks", ascending=False).head(1)
topper

       student class subject  marks
32  Student_33     B    Math     99

## **Topper per Subject**

In [8]:
subject_topper = df.loc[df.groupby("subject")["marks"].idxmax()]
subject_topper

       student class  subject  marks
28  Student_29     C  English     99
32  Student_33     B     Math     99
19  Student_20     B  Science     99

## **Pass/Fail Column**

In [9]:
df["result"] = df["marks"].apply(lambda x: "Pass" if x >= 40 else "Fail")

## **Pass/Fail Ratio**

In [10]:
pass_fail_ratio = df["result"].value_counts()
pass_fail_ratio

result
Pass    84
Fail    16
Name: count, dtype: int64

## **Pass Percentage per Class**

In [11]:
pass_percentage = (
    df[df["result"] == "Pass"]
    .groupby("class")
    .size() / df.groupby("class").size()
) * 100

pass_percentage.reset_index(name="pass_percentage")

  class  pass_percentage
0     A        90.909091
1     B        83.333333
2     C        77.419355

## **Save Final Dataset**

In [12]:
df.to_csv("data/student_processed.csv", index=False)