## **Import**

In [1]:
import pandas as pd
import numpy as np

## **Create Dataset**

In [2]:
np.random.seed(42)

data = {
    "city": np.random.choice(["Lahore", "Karachi", "Islamabad"], 100),
    "product": np.random.choice(["Laptop", "Phone", "Tablet"], 100),
    "sales": np.random.randint(100, 1000, 100)
}

df = pd.DataFrame(data)

df.head()

        city product  sales
0  Islamabad  Tablet    791
1     Lahore  Tablet    212
2  Islamabad  Tablet    929
3  Islamabad  Laptop    596
4     Lahore  Tablet    541

## **Save Dataset**

In [3]:
df.to_csv("data/sales_data.csv", index=False)

## **Load Dataset**

In [4]:
df = pd.read_csv("data/sales_data.csv")

## **Sales by City**

In [5]:
city_sales = df.groupby("city")["sales"].sum().reset_index()
city_sales

        city  sales
0  Islamabad  17466
1    Karachi  20843
2     Lahore  17124

## **Sales by Product**

In [6]:
product_sales = df.groupby("product")["sales"].sum().reset_index()
product_sales

  product  sales
0  Laptop  19230
1   Phone  12736
2  Tablet  23467

## **City + Product Analysis**

In [7]:
city_product_sales = df.groupby(["city", "product"])["sales"].sum().reset_index()
city_product_sales

        city product  sales
0  Islamabad  Laptop   5737
1  Islamabad   Phone   3400
2  Islamabad  Tablet   8329
3    Karachi  Laptop   6922
4    Karachi   Phone   6761
5    Karachi  Tablet   7160
6     Lahore  Laptop   6571
7     Lahore   Phone   2575
8     Lahore  Tablet   7978

## **Average Sales**

In [8]:
avg_sales = df.groupby("city")["sales"].mean().reset_index()
avg_sales

        city       sales
0  Islamabad  563.419355
1    Karachi  578.972222
2     Lahore  518.909091

## **Best Performing City**

In [9]:
best_city = city_sales.sort_values(by="sales", ascending=False).head(1)
best_city

      city  sales
1  Karachi  20843

## **Worst Performing City**

In [10]:
worst_product = product_sales.sort_values(by="sales").head(1)
worst_product

  product  sales
1   Phone  12736