## **Import**

In [1]:
import pandas as pd
import seaborn as sns

## **Load Dataset**

In [2]:
df = sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

## **Select Categorical Columns**

In [3]:
cat_cols = df.select_dtypes(include=['object', 'category']).columns
cat_cols

C:\Users\M.Hanzlah Azam\AppData\Local\Temp\ipykernel_12032\3532640940.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(include=['object', 'category']).columns

Index(['sex', 'embarked', 'class', 'who', 'deck', 'embark_town', 'alive'], dtype='str')

## **Text Cleaning**

In [4]:
for col in cat_cols:
    df[col] = df[col].astype(str).str.lower().str.strip()

## **Value Standardization (Example)**

In [5]:
# Standardizing 'sex' column
df['sex'] = df['sex'].replace({
    'male': 'male',
    'female': 'female'
})

## **Label Encoding (Binary Columns)**

In [6]:
df['sex'] = df['sex'].map({'male': 1, 'female': 0})

## **One-Hot Encoding**

In [7]:
df_encoded = pd.get_dummies(df, columns=['embarked', 'class'], drop_first=True)
df_encoded.head()

,survived,pclass,sex,age,sibsp,parch,fare,who,adult_male,deck,embark_town,alive,alone,embarked_q,embarked_s,class_second,class_third
0,0,3,1,22.0,1,0,7.2500,man,True,NaN,southampton,no,False,False,True,False,True
1,1,1,0,38.0,1,0,71.2833,woman,False,c,cherbourg,yes,False,False,False,False,False
2,1,3,0,26.0,0,0,7.9250,woman,False,NaN,southampton,yes,True,False,True,False,True
3,1,1,0,35.0,1,0,53.1000,woman,False,c,southampton,yes,False,False,True,False,False
4,0,3,1,35.0,0,0,8.0500,man,True,NaN,southampton,no,True,False,True,False,True

## **Check Result**

In [8]:
df_encoded.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   survived      891 non-null    int64
 1   pclass        891 non-null    int64
 2   sex           891 non-null    int64
 3   age           714 non-null    float64
 4   sibsp         891 non-null    int64
 5   parch         891 non-null    int64
 6   fare          891 non-null    float64
 7   who           891 non-null    str
 8   adult_male    891 non-null    bool
 9   deck          203 non-null    str
 10  embark_town   889 non-null    str
 11  alive         891 non-null    str
 12  alone         891 non-null    bool
 13  embarked_q    891 non-null    bool
 14  embarked_s    891 non-null    bool
 15  class_second  891 non-null    bool
 16  class_third   891 non-null    bool
dtypes: bool(6), float64(2), int64(5), str(4)
memory usage: 81.9 KB

## **Save Processed Data**

In [9]:
df_encoded.to_csv("data/titanic_processed.csv", index=False)