## **Import**

In [1]:
import pandas as pd
import numpy as np

## **Import**

In [9]:
df = pd.read_csv("data/train.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## **Initial Inspection**

In [10]:
df.shape

(891, 12)

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [12]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

## **Data Cleaning**

In [13]:
df = df.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)

df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])
df['Age'] = df['Age'].fillna(df['Age'].median())

## **Feature Engineering**

In [14]:
df['Family_Size'] = df['SibSp'] + df['Parch'] + 1

df['Alone'] = (df['Family_Size'] == 1).astype(int)

## **Drop Unnecessary Columns**

In [15]:
df = df.drop(['SibSp', 'Parch'], axis=1)

## **Encoding**

In [16]:
df = pd.get_dummies(df, columns=['Embarked'], drop_first=True)
df = pd.get_dummies(df, columns=['Sex'], drop_first=True)

## **Final Validation**

In [17]:
df.isnull().sum()

Survived       0
Pclass         0
Age            0
Fare           0
Family_Size    0
Alone          0
Embarked_Q     0
Embarked_S     0
Sex_male       0
dtype: int64

In [18]:
df.dtypes

Survived         int64
Pclass           int64
Age            float64
Fare           float64
Family_Size      int64
Alone            int64
Embarked_Q        bool
Embarked_S        bool
Sex_male          bool
dtype: object

## **Quick Sanity Check**

In [19]:
df.describe()

         Survived      Pclass         Age        Fare  Family_Size       Alone
count  891.000000  891.000000  891.000000  891.000000   891.000000  891.000000
mean     0.383838    2.308642   29.361582   32.204208     1.904602    0.602694
std      0.486592    0.836071   13.019697   49.693429     1.613459    0.489615
min      0.000000    1.000000    0.420000    0.000000     1.000000    0.000000
25%      0.000000    2.000000   22.000000    7.910400     1.000000    0.000000
50%      0.000000    3.000000   28.000000   14.454200     1.000000    1.000000
75%      1.000000    3.000000   35.000000   31.000000     2.000000    1.000000
max      1.000000    3.000000   80.000000  512.329200    11.000000    1.000000

## **Save Final Dataset**

In [20]:
df.to_csv("data/titanic_final.csv", index=False)